language: node_js
os:
  - osx
  - linux
node_js: 10

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - |
    echo ">>> Compile vscode-test"
    npm install && npm run compile
    echo ">>> Compiled vscode-test"
    echo ">>> Run integration tests"
    npm test
cache: npm