name: ci

on: [ push, pull_request ]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [ 10.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Execute tests (Linux)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Execute tests (MacOS, Windows)
      run: npm test
      if: runner.os != 'Linux'
